const contractAddress = "YOUR CONTRACT ADDRESS"; // Replace with your own contract address
const chain = 'rinkeby'; // rinkeby, polygon, or ethereum

const welcome_h1 = "Welcome to the Responsible Horse NFT Bonanza!!";
const welcome_h2 = "Hitch up to MetaMask to Get Started";
const welcome_p = 'A Ruff n Tumble Rip Roarin and Growin NFT collection!';
const h1_presale_coming_soon = "Bounty Drop Coming Soon!!";
const h1_presale_mint = "Pre-Sale Minting Open!!";
const h1_public_mint = "Public Minting Open!!";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Public Minting Countdown";
const p_presale_coming_soon = "Stay tuned while we wrangle up some updates!";
const p_presale_mint_not_whitelisted = "You ain't whitelisted for the pre-sale.. 😢";
const p_presale_mint_whitelisted = "You've staked your claim on the Whitelist! 🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 🎉";
const p_public_mint = "That whitelist don't hunt. Public minting is now open! 🎉";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Mint Your Special NFT";
const button_presale_mint_not_whitelisted = "Get on the Whitelist";
const button_presale_already_minted = "Join The Saloon";
const button_public_mint = "Mint Your NFT";
const mint_failed = "Minting failed, buckaroo. 😢 Get back in the saddle and try again.";
